import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react'

export type Language = 'en' | 'pt' | 'fr'

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

// Translation keys
const translations = {
  en: {
    // Dashboard
    'dashboard.title': 'Dashboard',
    'dashboard.welcome': 'Welcome to Owner Portal',
    'dashboard.overview': 'Overview',
    'dashboard.properties': 'Properties',
    'dashboard.bookings': 'Bookings',
    'dashboard.revenue': 'Revenue',
    'dashboard.occupancy': 'Occupancy Rate',
    'dashboard.averageRate': 'Average Rate',
    'dashboard.totalRevenue': 'Total Revenue',
    'dashboard.totalBookings': 'Total Bookings',
    'dashboard.activeProperties': 'Active Properties',
    'dashboard.pendingReviews': 'Pending Reviews',
    'dashboard.description': 'Here\'s what\'s happening with your properties today. Manage your portfolio with ease and maximize your rental income.',
    'dashboard.recentBookings': 'Recent Bookings',
    'dashboard.latestReservations': 'Latest reservations across your properties',
    'dashboard.quickActions': 'Quick Actions',
    'dashboard.manageEfficiently': 'Manage your properties efficiently',
    'dashboard.yourProperties': 'Your Properties',
    'dashboard.managePortfolio': 'Manage and monitor your property portfolio',
    'dashboard.viewCalendar': 'View Calendar',
    'dashboard.manageBookings': 'Manage Bookings',
    'dashboard.viewInvoices': 'View Invoices',
    'dashboard.getSAFT': 'Get SAFT-T',
    'dashboard.noBookings': 'No recent bookings found',
    'dashboard.bookingsWillAppear': 'Bookings will appear here once you have reservations',
    'dashboard.activePropertiesCount': 'Active Properties',
    'dashboard.noPropertiesFound': 'No Properties Found',
    'dashboard.addFirstProperty': 'Add your first property to start tracking bookings and revenue',
    'greeting.morning': 'Good morning',
    'greeting.afternoon': 'Good afternoon',
    'greeting.evening': 'Good evening',
    
    // Property Management
    'property.name': 'Property Name',
    'property.address': 'Address',
    'property.type': 'Type',
    'property.status': 'Status',
    'property.guests': 'Max Guests',
    'property.bedrooms': 'Bedrooms',
    'property.bathrooms': 'Bathrooms',
    'property.amenities': 'Amenities',
    'property.actions': 'Actions',
    'property.edit': 'Edit',
    'property.delete': 'Delete',
    'property.view': 'View',
    'property.bookings': 'Bookings',
    'property.invoices': 'Invoices',
    'property.calendar': 'Calendar',
    'property.add': 'Add Property',
    
    // Admin Panel
    'admin.dashboard': 'Admin Dashboard',
    'admin.welcomeBack': 'Welcome back',
    'admin.allOwners': 'All Owners',
    'admin.allAccountants': 'All Accountants',
    'admin.addUser': 'Add User',
    'admin.totalOwners': 'Total Owners',
    'admin.totalAccountants': 'Total Accountants',
    'admin.totalProperties': 'Total Properties',
    'admin.totalRevenue': 'Total Revenue',
    'admin.loadingDashboard': 'Loading Admin Dashboard...',
    'admin.ownersManagement': 'Owners Management',
    'admin.manageOwners': 'Manage property owners and their company information',
    'admin.addOwner': 'Add Owner',
    'admin.propertiesAllOwners': 'Properties (All Owners)',
    'admin.managePortfolio': 'Manage and monitor your property portfolio',
    'admin.addProperty': 'Add Property',
    'admin.accountantsAllAccountants': 'Accountants (All Accountants)',
    'admin.manageAccountants': 'Manage accountant access and property assignments',
    'admin.noAccountants': 'No accountants',
    'admin.getStartedAddAccountant': 'Get started by adding a new accountant',
    'admin.getStartedAddOwner': 'Get started by adding your first property owner',
    'admin.getStartedAddProperty': 'Get started by adding a new property',
    'admin.currentView': 'Current View',
    'admin.adminOwned': 'Admin Owned',
    'admin.ownerOwned': 'Owner Owned',
    'admin.edit': 'Edit',
    'admin.delete': 'Delete',
    'admin.verified': 'Verified',
    'admin.company': 'company',
    'admin.companies': 'companies',
    'admin.pending': 'Pending',
    'admin.owner': 'Owner',
    'admin.accountant': 'Accountant',
    'admin.id': 'ID',
    'admin.active': 'active',
    
    // Bookings
    'bookings.title': 'Bookings',
    'bookings.manageReservations': 'Manage reservations and guest communications',
    'bookings.loading': 'Loading bookings...',
    'bookings.selectProperty': 'Please select a property to view its bookings.',
    'bookings.showingData': 'Showing {period} data',
    'bookings.forProperty': 'for Property {propertyId}',
    'bookings.dateRange': '({startDate} to {endDate})',
    'bookings.clearFilters': 'Clear Filters',
    'bookings.property': 'Property:',
    'bookings.status': 'Status',
    'bookings.allStatuses': 'All Statuses',
    'bookings.modified': 'Modified',
    'bookings.inquiry': 'Inquiry',
    'bookings.inquiryPreapproved': 'Inquiry Pre-approved',
    'bookings.cancelled': 'Cancelled',
    'bookings.dateRangeLabel': 'Date Range',
    'bookings.selectDateRange': 'Select Date Range',
    'bookings.lastMonth': 'Last Month',
    'bookings.last3Months': 'Last 3 Months',
    'bookings.checkinFrom': 'Check-in From',
    'bookings.checkinTo': 'Check-in To',
    'bookings.clearAll': 'Clear All',
    'bookings.applyFilters': 'Apply Filters',
    'bookings.guest': 'Guest',
    'bookings.propertyLabel': 'Property',
    'bookings.checkin': 'Check-in',
    'bookings.checkout': 'Check-out',
    'bookings.amount': 'Amount',
    'bookings.actions': 'Actions',
    'bookings.viewDetails': 'View Details',
    'bookings.bookingDetails': 'Booking Details & SIBA Manager',
    'bookings.bookingInformation': 'Booking Information',
    'bookings.guestName': 'Guest Name:',
    'bookings.propertyColon': 'Property:',
    'bookings.checkinLabel': 'Check-in:',
    'bookings.checkoutLabel': 'Check-out:',
    'bookings.adults': 'Adults:',
    'bookings.children': 'Children:',
    'bookings.nights': 'Nights:',
    'bookings.platform': 'Platform:',
    'bookings.totalAmount': 'Total Amount:',
    'bookings.noBookingsFound': 'No bookings found',
    'bookings.selectPropertyFirst': 'Please select a property to view bookings',
    
    // Calendar
    'calendar.title': 'Property Calendar',
    'calendar.loading': 'Loading Calendar...',
    'calendar.noPropertySelected': 'No Property Selected',
    'calendar.selectPropertyToView': 'Please select a property to view its calendar and bookings.',
    'calendar.viewOnly': 'View Only',
    'calendar.manageAvailability': 'Manage your property availability and view bookings',
    'calendar.viewAvailability': 'View availability and bookings (read-only)',
    'calendar.day.sun': 'Sun',
    'calendar.day.mon': 'Mon',
    'calendar.day.tue': 'Tue',
    'calendar.day.wed': 'Wed',
    'calendar.day.thu': 'Thu',
    'calendar.day.fri': 'Fri',
    'calendar.day.sat': 'Sat',
    'calendar.status.booked': 'Booked',
    'calendar.status.blocked': 'Blocked',
    'calendar.status.available': 'Available',
    'calendar.status.guestDetails': 'Guest Details',
    'calendar.selected': 'Selected: {start} to {end}',
    'calendar.clickToBlockUnblock': 'Click to block or unblock these dates',
    'calendar.blockDates': 'Block Dates',
    'calendar.unblockDates': 'Unblock Dates',
    'calendar.cancel': 'Cancel',
    'calendar.multiDateSelection': 'Multi-Date Selection',
    'calendar.selectionInstructions': 'Click "Start Selection" → Click start date → Hover to end date → Click end date',
    'calendar.startSelection': 'Start Selection',
    'calendar.selectingDateRange': 'Selecting Date Range',
    'calendar.hoverToPreview': 'Hover to preview range, then click to complete selection',
    'calendar.doubleClickMode': 'Double-Click Mode: {count} date{plural} selected',
    'calendar.hoverToAdd': 'Hover over dates to add them to selection',
    'calendar.blockAll': 'Block All ({count})',
    'calendar.unblockAll': 'Unblock All ({count})',
    'calendar.exitMode': 'Exit Mode',
    'calendar.manageDate': 'Manage Date',
    'calendar.selectedDate': 'Selected Date:',
    'calendar.dateStatus': 'Date Status:',
    'calendar.unblockDate': 'Unblock Date',
    'calendar.blockDate': 'Block Date',
    'calendar.dateBookedCannotBlock': 'This date is booked and cannot be blocked or unblocked.',
    'calendar.loadingDateData': 'Loading date data...',
    'calendar.loadingShort': 'Loading...',
    'calendar.blockedCaps': 'BLOCKED',
    'calendar.reserved': 'RESERVED',
    'calendar.nightsMin': 'nights min',
    'calendar.guests': 'guests',
    'calendar.onlyOwnersCanManage': 'Only owners can manage calendar dates',
    'calendar.onlyOwnersCanManageAlert': 'Only owners can manage calendar dates. You can view the calendar but cannot make changes.',
    'calendar.sessionExpired': 'Your session has expired. Please refresh the page to continue.',
    'invoices.title': 'Invoices',
    'invoices.manageGuestInvoices': 'Manage guest invoices and billing',
    'invoices.loading': 'Loading Invoices...',
    'invoices.filters': 'Filters',
    'invoices.property': 'Property',
    'invoices.dateRange': 'Date Range',
    'invoices.fromDate': 'From Date',
    'invoices.toDate': 'To Date',
    'invoices.lastMonth': 'Last Month',
    'invoices.last3Months': 'Last 3 Months',
    'invoices.clearAll': 'Clear All',
    'invoices.applyFilters': 'Apply Filters',
    'invoices.noInvoicesFound': 'No invoices found',
    'invoices.noInvoicesAvailable': 'No invoices are currently available for this property.',
    'invoices.invoice': 'Invoice',
    'invoices.guest': 'Guest',
    'invoices.propertyLabel': 'Property',
    'invoices.date': 'Date',
    'invoices.amount': 'Amount',
    'invoices.status': 'Status',
    'invoices.actions': 'Actions',
    'invoices.closed': 'Closed',
    'invoices.open': 'Open',
    'invoices.downloading': 'Downloading...',
    'invoices.downloadInvoice': 'Download Invoice',
    'saft.title': 'SAFT-T Retrieval',
    'saft.description': 'Retrieve existing SAFT (Sistema de Apuramento de Faturas e Transações) files for Portuguese tax compliance.',
    'saft.companySelection': 'Company Selection',
    'saft.selectCompany': 'Select a company...',
    'saft.enterNifManually': 'Or enter NIF manually:',
    'saft.nifPlaceholder': 'e.g., 234567890',
    'saft.year': 'Year',
    'saft.month': 'Month',
    'saft.retrieving': 'Retrieving...',
    'saft.retrieveSaft': 'Retrieve SAFT-T',
    'saft.downloading': 'Downloading...',
    'saft.downloadSaft': 'Download SAFT-T',
    'saft.saftNotAvailable': 'SAFT File Not Available',
    'saft.tipNotGenerated': '💡 Tip: SAFT files are typically generated at the end of each month. Try selecting a previous month.',
    'saft.retrievedSuccessfully': 'SAFT-T Retrieved Successfully',
    'saft.generated': 'Generated',
    'saft.sent': 'Sent',
    'saft.downloadSaftFile': 'Download SAFT-T File',
    'saft.aboutSaft': 'About SAFT-T',
    'saft.aboutDescription1': 'The SAFT-T (Sistema de Apuramento de Faturas e Transações - Transmissão) is a Portuguese tax compliance system that requires businesses to submit detailed transaction data to the tax authorities. This tool helps you retrieve existing SAFT-T files for the specified period and invoicing VAT ID.',
    'saft.aboutDescription2': 'The SAFT-T file contains all invoice and transaction data and can be submitted directly to the Portuguese tax authorities.',
    'saft.month.january': 'January',
    'saft.month.february': 'February',
    'saft.month.march': 'March',
    'saft.month.april': 'April',
    'saft.month.may': 'May',
    'saft.month.june': 'June',
    'saft.month.july': 'July',
    'saft.month.august': 'August',
    'saft.month.september': 'September',
    'saft.month.october': 'October',
    'saft.month.november': 'November',
    'saft.month.december': 'December',
    'ownerStatements.title': 'Owner Statements',
    'ownerStatements.description': 'Generate financial statements for property owners',
    'ownerStatements.property': 'Property',
    'ownerStatements.selectProperty': 'Select Property',
    'ownerStatements.startDate': 'Start Date',
    'ownerStatements.endDate': 'End Date',
    'ownerStatements.managementCommissionRate': 'Management Commission Rate (Ignored for admin properties)',
    'ownerStatements.generating': 'Generating...',
    'ownerStatements.generateStatements': 'Generate Statements',
    'ownerStatements.generatingStatements': 'Generating statements...',
    'ownerStatements.propertyInformation': 'Property Information',
    'ownerStatements.propertyName': 'Property Name:',
    'ownerStatements.propertyId': 'Property ID:',
    'ownerStatements.status': 'Status:',
    'ownerStatements.period': 'Period:',
    'ownerStatements.created': 'Created:',
    'ownerStatements.commissionRate': 'Commission Rate:',
    'ownerStatements.detailedFinancialBreakdown': 'Detailed Financial Breakdown',
    'ownerStatements.downloadCsv': 'Download CSV',
    'ownerStatements.downloadPdf': 'Download PDF',
    'ownerStatements.detailedReport': 'DETAILED REPORT',
    'ownerStatements.propertyOwner': 'Property Owner',
    'ownerStatements.calculationBasis': 'Calculation basis:',
    'ownerStatements.commissionableAmount': 'Commissionable amount:',
    'ownerStatements.commissionableAmountNote': '',
    'ownerStatements.rule': 'Rule:',
    'ownerStatements.managementCommissions': 'Management commissions:',
    'ownerStatements.cleaningFees': 'Cleaning fees:',
    'ownerStatements.cleaningFeesNote': 'incl. VAT',
    'ownerStatements.hostCommissions': 'Host commissions:',
    'ownerStatements.extraFees': 'Extra fees:',
    'ownerStatements.expenses': 'Expenses:',
    'ownerStatements.issuer': 'Issuer:',
    'ownerStatements.recipient': 'Recipient:',
    'ownerStatements.totalToInvoice': 'TOTAL TO INVOICE:',
    'ownerStatements.tableProperty': 'Property',
    'ownerStatements.tableInvoice': 'Invoice',
    'ownerStatements.tableReservation': 'Reservation',
    'ownerStatements.tableReceivedAmount': 'Received amount',
    'ownerStatements.tableHostCommission': 'Host commission',
    'ownerStatements.tableCleaningFee': 'Cleaning fee',
    'ownerStatements.tableMgmtCommission': 'Mgmt commission',
    'ownerStatements.tableTotal': 'Total',
    
    // SIBA Manager
    'sibaManager.title': 'SIBA Manager Dashboard',
    'sibaManager.underDevelopment': 'Under Development',
    'sibaManager.description': 'We are currently working on enhancing the SIBA Manager Dashboard with new features and improvements. This section will be available soon with comprehensive SIBA compliance monitoring capabilities.',
    'sibaManager.comingSoon': 'Coming Soon',
    
    // Auth pages
    'auth.welcomeBack': 'Welcome back',
    'auth.signInToDashboard': 'Sign in to your property management dashboard',
    'auth.emailAddress': 'Email address',
    'auth.enterEmail': 'Enter your email',
    'auth.password': 'Password',
    'auth.enterPassword': 'Enter your password',
    'auth.sendOTP': 'Send OTP',
    'auth.forgotPassword': 'Forgot your password?',
    'auth.noAccount': 'Don\'t have an account?',
    'auth.signUpFree': 'Sign up for free',
    'auth.forgotPasswordTitle': 'Forgot your password?',
    'auth.forgotPasswordDescription': 'No worries! Enter your email and we\'ll send you a reset OTP.',
    'auth.sendResetOTP': 'Send reset OTP',
    'auth.backToLogin': 'Back to login',
    'auth.resetPasswordTitle': 'Reset your password',
    'auth.resetPasswordDescription': 'Enter your email, OTP code, and new password below.',
    'auth.accountCreation': 'Account Creation',
    'auth.contactAdmin': 'Contact your administrator to request account creation',
    'auth.firstName': 'First Name',
    'auth.lastName': 'Last Name',
    'auth.phoneNumber': 'Phone Number',
    'auth.confirmPassword': 'Confirm Password',
    'auth.enterFirstName': 'Enter your first name',
    'auth.enterLastName': 'Enter your last name',
    'auth.enterPhoneNumber': 'Enter your phone number',
    'auth.confirmYourPassword': 'Confirm your password',
    'auth.accountType': 'Account Type',
    'auth.adminAccountUnavailable': 'Admin Account (Unavailable)',
    'auth.alreadyExists': '(Already exists)',
    'auth.contactAdminForAccount': 'Contact Administrator for Account Creation',
    'auth.alreadyHaveAccount': 'Already have an account?',
    'auth.signInHere': 'Sign in here',
    'auth.accountCreationByAdmin': 'Account Creation by Administrator',
    'auth.allAccountsCreatedByAdmin': 'All user accounts are created by the system administrator. Please contact your administrator to request account creation.',
    'auth.toRequestAccount': 'To request an account:',
    'auth.contactSystemAdmin': 'Contact your system administrator',
    'auth.provideEmailAndRole': 'Provide your email address and role requirements',
    'auth.adminWillCreateAccount': 'Administrator will create your account and send login credentials',
    'marketing.manageProperties': 'Manage your properties with confidence',
    'marketing.platformDescription': 'Track bookings, monitor performance, handle compliance, and maximize your rental income with our comprehensive property management platform.',
    'marketing.realTimeBooking': 'Real-time booking management',
    'marketing.financialTracking': 'Financial performance tracking',
    'marketing.complianceReporting': 'Automated compliance reporting',
    'marketing.multiPropertyDashboard': 'Multi-property dashboard',
    'marketing.joinOwners': 'Join thousands of property owners',
    'marketing.journeyDescription': 'Start your property management journey with our comprehensive platform designed to maximize your rental income and streamline operations.',
    'marketing.easyOnboarding': 'Easy property onboarding',
    'marketing.automatedBookings': 'Automated booking management',
    'marketing.financialReporting': 'Financial reporting & analytics',
    'marketing.customerSupport': '24/7 customer support',
    
    // Booking Detail PDF
    'bookingDetail.reportTitle': 'Booking Detail Report',
    'bookingDetail.generatedOn': 'Generated on:',
    'bookingDetail.basicInformation': 'Basic Information',
    'bookingDetail.hostawayReservationId': 'Hostaway Reservation ID:',
    'bookingDetail.channelReservationId': 'Channel Reservation ID:',
    'bookingDetail.property': 'Property:',
    'bookingDetail.guestName': 'Guest Name:',
    'bookingDetail.guestEmail': 'Guest Email:',
    'bookingDetail.guestPhone': 'Guest Phone:',
    'bookingDetail.datesDuration': 'Dates & Duration',
    'bookingDetail.checkin': 'Check-in:',
    'bookingDetail.checkout': 'Check-out:',
    'bookingDetail.totalNights': 'Total Nights:',
    'bookingDetail.checkinTime': 'Check-in Time:',
    'bookingDetail.checkoutTime': 'Check-out Time:',
    'bookingDetail.guestInformation': 'Guest Information',
    'bookingDetail.adults': 'Adults:',
    'bookingDetail.children': 'Children:',
    'bookingDetail.totalGuests': 'Total Guests:',
    'bookingDetail.bookingDetails': 'Booking Details',
    'bookingDetail.platform': 'Platform:',
    'bookingDetail.status': 'Status:',
    'bookingDetail.paymentStatus': 'Payment Status:',
    'bookingDetail.financialBreakdown': 'Financial Breakdown',
    'bookingDetail.totalRevenue': 'Total Revenue:',
    'bookingDetail.finalAmountNote': 'Final amount - includes all fees (cleaning, city tax, etc.)',
    'bookingDetail.cityTax': 'City Tax:',
    'bookingDetail.specialRequests': 'Special Requests',
    'bookingDetail.notProvided': 'Not provided',
    'bookingDetail.backToBookings': 'Back to Bookings',
    'bookingDetail.printPdf': 'Print PDF',
    'bookingDetail.guestEmailNotProvided': 'Not provided by platform (privacy policy)',
    'bookingDetail.confirmed': 'Confirmed',
    'bookingDetail.modified': 'Modified',
    'bookingDetail.cancelled': 'Cancelled',
    'bookingDetail.pending': 'Pending',
    
    // Navigation
    'nav.dashboard': 'Dashboard',
    'nav.adminPanel': 'Admin Panel',
    'nav.ownerManagement': 'Owner Management',
    'nav.properties': 'Properties',
    'nav.bookings': 'Bookings',
    'nav.invoices': 'Invoices',
    'nav.sibaManager': 'SIBA Manager',
    'nav.saft': 'SAFT-T',
    'nav.calendar': 'Calendar',
    'nav.reviews': 'Reviews',
    'nav.performance': 'Performance',
    'nav.portfolio': 'Portfolio',
    'nav.creditNotes': 'Credit Notes',
    'nav.expenses': 'Expenses',
    'nav.ownerStatements': 'Owner Statements',
    'nav.settings': 'Settings',
    'nav.profile': 'Profile',
    'nav.signOut': 'Sign Out',
    
    // Common
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.success': 'Success',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.edit': 'Edit',
    'common.delete': 'Delete',
    'common.view': 'View',
    'common.close': 'Close',
    'common.yes': 'Yes',
    'common.no': 'No',
    'common.confirm': 'Confirm',
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.sort': 'Sort',
    'common.refresh': 'Refresh',
    
    // Language
    'language.english': 'English',
    'language.portuguese': 'Português',
    'language.french': 'Français',
    'language.switch': 'Switch Language',
    
    // Status
    'status.active': 'Active',
    'status.inactive': 'Inactive',
    'status.pending': 'Pending',
    'status.completed': 'Completed',
    'status.cancelled': 'Cancelled',
    
    // Calendar
    'calendar.month': 'Month',
    'calendar.week': 'Week',
    'calendar.day': 'Day',
    'calendar.today': 'Today',
    'calendar.booked': 'Booked',
    'calendar.available': 'Available',
    'calendar.blocked': 'Blocked',
    'calendar.price': 'Price',
    'calendar.minStay': 'Min Stay',
    
    // Notifications
    'notification.newBooking': 'New Booking',
    'notification.paymentReceived': 'Payment Received',
    'notification.reviewReceived': 'New Review',
    'notification.maintenanceRequest': 'Maintenance Request',
    'notification.title': 'Notifications',
    'notification.markAllRead': 'Mark all read',
    'notification.noNotifications': 'No notifications',
  },
  pt: {
    // Dashboard
    'dashboard.title': 'Painel de Controle',
    'dashboard.welcome': 'Bem-vindo ao Portal do Proprietário',
    'dashboard.overview': 'Visão Geral',
    'dashboard.properties': 'Propriedades',
    'dashboard.bookings': 'Reservas',
    'dashboard.revenue': 'Receita',
    'dashboard.occupancy': 'Taxa de Ocupação',
    'dashboard.averageRate': 'Taxa Média',
    'dashboard.totalRevenue': 'Receita Total',
    'dashboard.totalBookings': 'Total de Reservas',
    'dashboard.activeProperties': 'Propriedades Ativas',
    'dashboard.pendingReviews': 'Avaliações Pendentes',
    'dashboard.description': 'Aqui está o que está acontecendo com suas propriedades hoje. Gerencie seu portfólio com facilidade e maximize sua receita de aluguel.',
    'dashboard.recentBookings': 'Reservas Recentes',
    'dashboard.latestReservations': 'Últimas reservas em suas propriedades',
    'dashboard.quickActions': 'Ações Rápidas',
    'dashboard.manageEfficiently': 'Gerencie suas propriedades com eficiência',
    'dashboard.yourProperties': 'Suas Propriedades',
    'dashboard.managePortfolio': 'Gerencie e monitore seu portfólio de propriedades',
    'dashboard.viewCalendar': 'Ver Calendário',
    'dashboard.manageBookings': 'Gerenciar Reservas',
    'dashboard.viewInvoices': 'Ver Faturas',
    'dashboard.getSAFT': 'Obter SAFT-T',
    'dashboard.noBookings': 'Nenhuma reserva recente encontrada',
    'dashboard.bookingsWillAppear': 'As reservas aparecerão aqui assim que você tiver reservas',
    'dashboard.activePropertiesCount': 'Propriedades Ativas',
    'dashboard.noPropertiesFound': 'Nenhuma Propriedade Encontrada',
    'dashboard.addFirstProperty': 'Adicione sua primeira propriedade para começar a rastrear reservas e receita',
    'greeting.morning': 'Bom dia',
    'greeting.afternoon': 'Boa tarde',
    'greeting.evening': 'Boa noite',
    
    // Property Management
    'property.name': 'Nome da Propriedade',
    'property.address': 'Endereço',
    'property.type': 'Tipo',
    'property.status': 'Status',
    'property.guests': 'Hóspedes Máx',
    'property.bedrooms': 'Quartos',
    'property.bathrooms': 'Banheiros',
    'property.amenities': 'Comodidades',
    'property.actions': 'Ações',
    'property.edit': 'Editar',
    'property.delete': 'Excluir',
    'property.view': 'Visualizar',
    'property.bookings': 'Reservas',
    'property.invoices': 'Faturas',
    'property.calendar': 'Calendário',
    'property.add': 'Adicionar Propriedade',
    
    // Admin Panel
    'admin.dashboard': 'Painel de Administração',
    'admin.welcomeBack': 'Bem-vindo de volta',
    'admin.allOwners': 'Todos os Proprietários',
    'admin.allAccountants': 'Todos os Contadores',
    'admin.addUser': 'Adicionar Usuário',
    'admin.totalOwners': 'Total de Proprietários',
    'admin.totalAccountants': 'Total de Contadores',
    'admin.totalProperties': 'Total de Propriedades',
    'admin.totalRevenue': 'Receita Total',
    'admin.loadingDashboard': 'Carregando Painel de Administração...',
    'admin.ownersManagement': 'Gestão de Proprietários',
    'admin.manageOwners': 'Gerir proprietários e suas informações da empresa',
    'admin.addOwner': 'Adicionar Proprietário',
    'admin.propertiesAllOwners': 'Propriedades (Todos os Proprietários)',
    'admin.managePortfolio': 'Gerir e monitorizar o seu portfólio de propriedades',
    'admin.addProperty': 'Adicionar Propriedade',
    'admin.accountantsAllAccountants': 'Contadores (Todos os Contadores)',
    'admin.manageAccountants': 'Gerir acesso de contadores e atribuições de propriedades',
    'admin.noAccountants': 'Nenhum contador',
    'admin.getStartedAddAccountant': 'Comece adicionando um novo contador',
    'admin.getStartedAddOwner': 'Comece adicionando seu primeiro proprietário',
    'admin.getStartedAddProperty': 'Comece adicionando uma nova propriedade',
    'admin.currentView': 'Visualização Atual',
    'admin.adminOwned': 'Propriedade Admin',
    'admin.ownerOwned': 'Propriedade do Proprietário',
    'admin.edit': 'Editar',
    'admin.delete': 'Excluir',
    'admin.verified': 'Verificado',
    'admin.company': 'empresa',
    'admin.companies': 'empresas',
    'admin.pending': 'Pendente',
    'admin.owner': 'Proprietário',
    'admin.accountant': 'Contador',
    'admin.id': 'ID',
    'admin.active': 'ativo',
    
    // Bookings
    'bookings.title': 'Reservas',
    'bookings.manageReservations': 'Gerir reservas e comunicações com hóspedes',
    'bookings.loading': 'Carregando reservas...',
    'bookings.selectProperty': 'Por favor, selecione uma propriedade para ver as suas reservas.',
    'bookings.showingData': 'Mostrando dados {period}',
    'bookings.forProperty': 'para a propriedade {propertyId}',
    'bookings.dateRange': '({startDate} a {endDate})',
    'bookings.clearFilters': 'Limpar filtros',
    'bookings.property': 'Propriedade:',
    'bookings.status': 'Status',
    'bookings.allStatuses': 'Todos os status',
    'bookings.modified': 'Modificado',
    'bookings.inquiry': 'Consulta',
    'bookings.inquiryPreapproved': 'Consulta pré-aprovada',
    'bookings.cancelled': 'Cancelado',
    'bookings.dateRangeLabel': 'Intervalo de datas',
    'bookings.selectDateRange': 'Selecionar intervalo de datas',
    'bookings.lastMonth': 'Mês passado',
    'bookings.last3Months': 'Últimos 3 meses',
    'bookings.checkinFrom': 'Check-in de',
    'bookings.checkinTo': 'Check-in até',
    'bookings.clearAll': 'Limpar tudo',
    'bookings.applyFilters': 'Aplicar filtros',
    'bookings.guest': 'Hóspede',
    'bookings.propertyLabel': 'Propriedade',
    'bookings.checkin': 'Check-in',
    'bookings.checkout': 'Check-out',
    'bookings.amount': 'Valor',
    'bookings.actions': 'Ações',
    'bookings.viewDetails': 'Ver detalhes',
    'bookings.bookingDetails': 'Detalhes da reserva e gerenciador SIBA',
    'bookings.bookingInformation': 'Informações da reserva',
    'bookings.guestName': 'Nome do hóspede:',
    'bookings.propertyColon': 'Propriedade:',
    'bookings.checkinLabel': 'Check-in:',
    'bookings.checkoutLabel': 'Check-out:',
    'bookings.adults': 'Adultos:',
    'bookings.children': 'Crianças:',
    'bookings.nights': 'Noites:',
    'bookings.platform': 'Plataforma:',
    'bookings.totalAmount': 'Valor total:',
    'bookings.noBookingsFound': 'Nenhuma reserva encontrada',
    'bookings.selectPropertyFirst': 'Por favor, selecione uma propriedade para ver as reservas',
    
    // Calendar
    'calendar.title': 'Calendário da Propriedade',
    'calendar.loading': 'Carregando Calendário...',
    'calendar.noPropertySelected': 'Nenhuma Propriedade Selecionada',
    'calendar.selectPropertyToView': 'Por favor, selecione uma propriedade para ver seu calendário e reservas.',
    'calendar.viewOnly': 'Somente Leitura',
    'calendar.manageAvailability': 'Gerencie a disponibilidade da sua propriedade e visualize reservas',
    'calendar.viewAvailability': 'Visualize disponibilidade e reservas (somente leitura)',
    'calendar.day.sun': 'Dom',
    'calendar.day.mon': 'Seg',
    'calendar.day.tue': 'Ter',
    'calendar.day.wed': 'Qua',
    'calendar.day.thu': 'Qui',
    'calendar.day.fri': 'Sex',
    'calendar.day.sat': 'Sáb',
    'calendar.status.booked': 'Reservado',
    'calendar.status.blocked': 'Bloqueado',
    'calendar.status.available': 'Disponível',
    'calendar.status.guestDetails': 'Detalhes dos Hóspedes',
    'calendar.selected': 'Selecionado: {start} a {end}',
    'calendar.clickToBlockUnblock': 'Clique para bloquear ou desbloquear essas datas',
    'calendar.blockDates': 'Bloquear Datas',
    'calendar.unblockDates': 'Desbloquear Datas',
    'calendar.cancel': 'Cancelar',
    'calendar.multiDateSelection': 'Seleção Multi-Data',
    'calendar.selectionInstructions': 'Clique em "Iniciar Seleção" → Clique na data de início → Passe o mouse até a data final → Clique na data final',
    'calendar.startSelection': 'Iniciar Seleção',
    'calendar.selectingDateRange': 'Selecionando Intervalo de Datas',
    'calendar.hoverToPreview': 'Passe o mouse para visualizar o intervalo, depois clique para completar a seleção',
    'calendar.doubleClickMode': 'Modo Duplo-Clique: {count} data{plural} selecionada{plural}',
    'calendar.hoverToAdd': 'Passe o mouse sobre as datas para adicioná-las à seleção',
    'calendar.blockAll': 'Bloquear Tudo ({count})',
    'calendar.unblockAll': 'Desbloquear Tudo ({count})',
    'calendar.exitMode': 'Sair do Modo',
    'calendar.manageDate': 'Gerenciar Data',
    'calendar.selectedDate': 'Data Selecionada:',
    'calendar.dateStatus': 'Status da Data:',
    'calendar.unblockDate': 'Desbloquear Data',
    'calendar.blockDate': 'Bloquear Data',
    'calendar.dateBookedCannotBlock': 'Esta data está reservada e não pode ser bloqueada ou desbloqueada.',
    'calendar.loadingDateData': 'Carregando dados da data...',
    'calendar.loadingShort': 'Carregando...',
    'calendar.blockedCaps': 'BLOQUEADO',
    'calendar.reserved': 'RESERVADO',
    'calendar.nightsMin': 'noites mín',
    'calendar.guests': 'hóspedes',
    'calendar.onlyOwnersCanManage': 'Apenas proprietários podem gerenciar datas do calendário',
    'calendar.onlyOwnersCanManageAlert': 'Apenas proprietários podem gerenciar datas do calendário. Você pode visualizar o calendário mas não pode fazer alterações.',
    'calendar.sessionExpired': 'Sua sessão expirou. Por favor, atualize a página para continuar.',
    'invoices.title': 'Faturas',
    'invoices.manageGuestInvoices': 'Gerenciar faturas de hóspedes e cobrança',
    'invoices.loading': 'Carregando faturas...',
    'invoices.filters': 'Filtros',
    'invoices.property': 'Propriedade',
    'invoices.dateRange': 'Período',
    'invoices.fromDate': 'Data de início',
    'invoices.toDate': 'Data de fim',
    'invoices.lastMonth': 'Mês passado',
    'invoices.last3Months': 'Últimos 3 meses',
    'invoices.clearAll': 'Limpar tudo',
    'invoices.applyFilters': 'Aplicar filtros',
    'invoices.noInvoicesFound': 'Nenhuma fatura encontrada',
    'invoices.noInvoicesAvailable': 'Nenhuma fatura está atualmente disponível para esta propriedade.',
    'invoices.invoice': 'Fatura',
    'invoices.guest': 'Hóspede',
    'invoices.propertyLabel': 'Propriedade',
    'invoices.date': 'Data',
    'invoices.amount': 'Valor',
    'invoices.status': 'Status',
    'invoices.actions': 'Ações',
    'invoices.closed': 'Fechado',
    'invoices.open': 'Aberto',
    'invoices.downloading': 'Baixando...',
    'invoices.downloadInvoice': 'Baixar fatura',
    'saft.title': 'Recuperação SAFT-T',
    'saft.description': 'Recuperar arquivos SAFT (Sistema de Apuramento de Faturas e Transações) existentes para conformidade fiscal portuguesa.',
    'saft.companySelection': 'Seleção da Empresa',
    'saft.selectCompany': 'Selecionar uma empresa...',
    'saft.enterNifManually': 'Ou inserir NIF manualmente:',
    'saft.nifPlaceholder': 'ex., 234567890',
    'saft.year': 'Ano',
    'saft.month': 'Mês',
    'saft.retrieving': 'Recuperando...',
    'saft.retrieveSaft': 'Recuperar SAFT-T',
    'saft.downloading': 'Baixando...',
    'saft.downloadSaft': 'Baixar SAFT-T',
    'saft.saftNotAvailable': 'Arquivo SAFT não disponível',
    'saft.tipNotGenerated': '💡 Dica: Os arquivos SAFT são tipicamente gerados no final de cada mês. Tente selecionar um mês anterior.',
    'saft.retrievedSuccessfully': 'SAFT-T recuperado com sucesso',
    'saft.generated': 'Gerado',
    'saft.sent': 'Enviado',
    'saft.downloadSaftFile': 'Baixar arquivo SAFT-T',
    'saft.aboutSaft': 'Sobre SAFT-T',
    'saft.aboutDescription1': 'O SAFT-T (Sistema de Apuramento de Faturas e Transações - Transmissão) é um sistema de conformidade fiscal português que exige que as empresas submetam dados detalhados de transações às autoridades fiscais. Esta ferramenta ajuda você a recuperar arquivos SAFT-T existentes para o período e ID de IVA de faturação especificados.',
    'saft.aboutDescription2': 'O arquivo SAFT-T contém todos os dados de fatura e transação e pode ser submetido diretamente às autoridades fiscais portuguesas.',
    'saft.month.january': 'Janeiro',
    'saft.month.february': 'Fevereiro',
    'saft.month.march': 'Março',
    'saft.month.april': 'Abril',
    'saft.month.may': 'Maio',
    'saft.month.june': 'Junho',
    'saft.month.july': 'Julho',
    'saft.month.august': 'Agosto',
    'saft.month.september': 'Setembro',
    'saft.month.october': 'Outubro',
    'saft.month.november': 'Novembro',
    'saft.month.december': 'Dezembro',
    'ownerStatements.title': 'Declarações do Proprietário',
    'ownerStatements.description': 'Gerar declarações financeiras para proprietários',
    'ownerStatements.property': 'Propriedade',
    'ownerStatements.selectProperty': 'Selecionar Propriedade',
    'ownerStatements.startDate': 'Data de Início',
    'ownerStatements.endDate': 'Data de Fim',
    'ownerStatements.managementCommissionRate': 'Taxa de Comissão de Gestão (Ignorada para propriedades admin)',
    'ownerStatements.generating': 'Gerando...',
    'ownerStatements.generateStatements': 'Gerar Declarações',
    'ownerStatements.generatingStatements': 'Gerando declarações...',
    'ownerStatements.propertyInformation': 'Informações da Propriedade',
    'ownerStatements.propertyName': 'Nome da Propriedade:',
    'ownerStatements.propertyId': 'ID da Propriedade:',
    'ownerStatements.status': 'Status:',
    'ownerStatements.period': 'Período:',
    'ownerStatements.created': 'Criado:',
    'ownerStatements.commissionRate': 'Taxa de Comissão:',
    'ownerStatements.detailedFinancialBreakdown': 'Detalhamento Financeiro Detalhado',
    'ownerStatements.downloadCsv': 'Baixar CSV',
    'ownerStatements.downloadPdf': 'Baixar PDF',
    'ownerStatements.detailedReport': 'RELATÓRIO DETALHADO',
    'ownerStatements.propertyOwner': 'Proprietário da Propriedade',
    'ownerStatements.calculationBasis': 'Base de cálculo:',
    'ownerStatements.commissionableAmount': 'Valor comissionável:',
    'ownerStatements.commissionableAmountNote': '',
    'ownerStatements.rule': 'Regra:',
    'ownerStatements.managementCommissions': 'Comissões de gestão:',
    'ownerStatements.cleaningFees': 'Taxas de limpeza:',
    'ownerStatements.cleaningFeesNote': 'incl. IVA',
    'ownerStatements.hostCommissions': 'Comissões do anfitrião:',
    'ownerStatements.extraFees': 'Taxas extras:',
    'ownerStatements.expenses': 'Despesas:',
    'ownerStatements.issuer': 'Emissor:',
    'ownerStatements.recipient': 'Destinatário:',
    'ownerStatements.totalToInvoice': 'TOTAL A FATURAR:',
    'ownerStatements.tableProperty': 'Propriedade',
    'ownerStatements.tableInvoice': 'Fatura',
    'ownerStatements.tableReservation': 'Reserva',
    'ownerStatements.tableReceivedAmount': 'Valor recebido',
    'ownerStatements.tableHostCommission': 'Comissão do anfitrião',
    'ownerStatements.tableCleaningFee': 'Taxa de limpeza',
    'ownerStatements.tableMgmtCommission': 'Comissão de gestão',
    'ownerStatements.tableTotal': 'Total',
    
    // SIBA Manager
    'sibaManager.title': 'Painel do Gestor SIBA',
    'sibaManager.underDevelopment': 'Em Desenvolvimento',
    'sibaManager.description': 'Estamos atualmente trabalhando na melhoria do Painel do Gestor SIBA com novos recursos e melhorias. Esta seção estará disponível em breve com capacidades abrangentes de monitoramento de conformidade SIBA.',
    'sibaManager.comingSoon': 'Em Breve',
    
    // Auth pages
    'auth.welcomeBack': 'Bem-vindo de volta',
    'auth.signInToDashboard': 'Entre no seu painel de gerenciamento de propriedades',
    'auth.emailAddress': 'Endereço de email',
    'auth.enterEmail': 'Digite seu email',
    'auth.password': 'Senha',
    'auth.enterPassword': 'Digite sua senha',
    'auth.sendOTP': 'Enviar OTP',
    'auth.forgotPassword': 'Esqueceu sua senha?',
    'auth.noAccount': 'Não tem uma conta?',
    'auth.signUpFree': 'Cadastre-se gratuitamente',
    'auth.forgotPasswordTitle': 'Esqueceu sua senha?',
    'auth.forgotPasswordDescription': 'Sem problemas! Digite seu email e enviaremos um OTP de redefinição.',
    'auth.sendResetOTP': 'Enviar OTP de redefinição',
    'auth.backToLogin': 'Voltar ao login',
    'auth.resetPasswordTitle': 'Redefinir sua senha',
    'auth.resetPasswordDescription': 'Digite seu email, código OTP e nova senha abaixo.',
    'auth.accountCreation': 'Criação de Conta',
    'auth.contactAdmin': 'Entre em contato com seu administrador para solicitar a criação de conta',
    'auth.firstName': 'Primeiro Nome',
    'auth.lastName': 'Sobrenome',
    'auth.phoneNumber': 'Número de Telefone',
    'auth.confirmPassword': 'Confirmar Senha',
    'auth.enterFirstName': 'Digite seu primeiro nome',
    'auth.enterLastName': 'Digite seu sobrenome',
    'auth.enterPhoneNumber': 'Digite seu número de telefone',
    'auth.confirmYourPassword': 'Confirme sua senha',
    'auth.accountType': 'Tipo de Conta',
    'auth.adminAccountUnavailable': 'Conta de Administrador (Indisponível)',
    'auth.alreadyExists': '(Já existe)',
    'auth.contactAdminForAccount': 'Contatar Administrador para Criação de Conta',
    'auth.alreadyHaveAccount': 'Já tem uma conta?',
    'auth.signInHere': 'Entre aqui',
    'auth.accountCreationByAdmin': 'Criação de Conta pelo Administrador',
    'auth.allAccountsCreatedByAdmin': 'Todas as contas de usuário são criadas pelo administrador do sistema. Entre em contato com seu administrador para solicitar a criação de conta.',
    'auth.toRequestAccount': 'Para solicitar uma conta:',
    'auth.contactSystemAdmin': 'Entre em contato com seu administrador do sistema',
    'auth.provideEmailAndRole': 'Forneça seu endereço de email e requisitos de função',
    'auth.adminWillCreateAccount': 'O administrador criará sua conta e enviará as credenciais de login',
    'marketing.manageProperties': 'Gerencie suas propriedades com confiança',
    'marketing.platformDescription': 'Acompanhe reservas, monitore performance, gerencie conformidade e maximize sua receita de aluguel com nossa plataforma abrangente de gerenciamento de propriedades.',
    'marketing.realTimeBooking': 'Gerenciamento de reservas em tempo real',
    'marketing.financialTracking': 'Acompanhamento de performance financeira',
    'marketing.complianceReporting': 'Relatórios de conformidade automatizados',
    'marketing.multiPropertyDashboard': 'Painel multi-propriedades',
    'marketing.joinOwners': 'Junte-se a milhares de proprietários',
    'marketing.journeyDescription': 'Inicie sua jornada de gerenciamento de propriedades com nossa plataforma abrangente projetada para maximizar sua receita de aluguel e otimizar operações.',
    'marketing.easyOnboarding': 'Integração fácil de propriedades',
    'marketing.automatedBookings': 'Gerenciamento automatizado de reservas',
    'marketing.financialReporting': 'Relatórios e análises financeiras',
    'marketing.customerSupport': 'Suporte ao cliente 24/7',
    
    // Booking Detail PDF
    'bookingDetail.reportTitle': 'Relatório de Detalhes da Reserva',
    'bookingDetail.generatedOn': 'Gerado em:',
    'bookingDetail.basicInformation': 'Informações Básicas',
    'bookingDetail.hostawayReservationId': 'ID da Reserva Hostaway:',
    'bookingDetail.channelReservationId': 'ID da Reserva do Canal:',
    'bookingDetail.property': 'Propriedade:',
    'bookingDetail.guestName': 'Nome do Hóspede:',
    'bookingDetail.guestEmail': 'Email do Hóspede:',
    'bookingDetail.guestPhone': 'Telefone do Hóspede:',
    'bookingDetail.datesDuration': 'Datas e Duração',
    'bookingDetail.checkin': 'Check-in:',
    'bookingDetail.checkout': 'Check-out:',
    'bookingDetail.totalNights': 'Total de Noites:',
    'bookingDetail.checkinTime': 'Hora de Check-in:',
    'bookingDetail.checkoutTime': 'Hora de Check-out:',
    'bookingDetail.guestInformation': 'Informações do Hóspede',
    'bookingDetail.adults': 'Adultos:',
    'bookingDetail.children': 'Crianças:',
    'bookingDetail.totalGuests': 'Total de Hóspedes:',
    'bookingDetail.bookingDetails': 'Detalhes da Reserva',
    'bookingDetail.platform': 'Plataforma:',
    'bookingDetail.status': 'Status:',
    'bookingDetail.paymentStatus': 'Status do Pagamento:',
    'bookingDetail.financialBreakdown': 'Análise Financeira',
    'bookingDetail.totalRevenue': 'Receita Total:',
    'bookingDetail.finalAmountNote': 'Valor final - inclui todas as taxas (limpeza, taxa da cidade, etc.)',
    'bookingDetail.cityTax': 'Taxa da Cidade:',
    'bookingDetail.specialRequests': 'Pedidos Especiais',
    'bookingDetail.notProvided': 'Não fornecido',
    'bookingDetail.backToBookings': 'Voltar às Reservas',
    'bookingDetail.printPdf': 'Imprimir PDF',
    'bookingDetail.guestEmailNotProvided': 'Não fornecido pela plataforma (política de privacidade)',
    'bookingDetail.confirmed': 'Confirmado',
    'bookingDetail.modified': 'Modificado',
    'bookingDetail.cancelled': 'Cancelado',
    'bookingDetail.pending': 'Pendente',
    
    // Navigation
    'nav.dashboard': 'Painel',
    'nav.adminPanel': 'Painel Admin',
    'nav.ownerManagement': 'Gestão de Proprietários',
    'nav.properties': 'Propriedades',
    'nav.bookings': 'Reservas',
    'nav.invoices': 'Faturas',
    'nav.sibaManager': 'Gestor SIBA',
    'nav.saft': 'SAFT-T',
    'nav.calendar': 'Calendário',
    'nav.reviews': 'Avaliações',
    'nav.performance': 'Desempenho',
    'nav.portfolio': 'Portfólio',
    'nav.creditNotes': 'Notas de Crédito',
    'nav.expenses': 'Despesas',
    'nav.ownerStatements': 'Extratos do Proprietário',
    'nav.settings': 'Configurações',
    'nav.profile': 'Perfil',
    'nav.signOut': 'Sair',
    
    // Common
    'common.loading': 'Carregando...',
    'common.error': 'Erro',
    'common.success': 'Sucesso',
    'common.save': 'Salvar',
    'common.cancel': 'Cancelar',
    'common.edit': 'Editar',
    'common.delete': 'Excluir',
    'common.view': 'Visualizar',
    'common.close': 'Fechar',
    'common.yes': 'Sim',
    'common.no': 'Não',
    'common.confirm': 'Confirmar',
    'common.search': 'Pesquisar',
    'common.filter': 'Filtrar',
    'common.sort': 'Ordenar',
    'common.refresh': 'Atualizar',
    
    // Language
    'language.english': 'English',
    'language.portuguese': 'Português',
    'language.switch': 'Alterar Idioma',
    
    // Status
    'status.active': 'Ativo',
    'status.inactive': 'Inativo',
    'status.pending': 'Pendente',
    'status.completed': 'Concluído',
    'status.cancelled': 'Cancelado',
    
    // Calendar
    'calendar.month': 'Mês',
    'calendar.week': 'Semana',
    'calendar.day': 'Dia',
    'calendar.today': 'Hoje',
    'calendar.booked': 'Reservado',
    'calendar.available': 'Disponível',
    'calendar.blocked': 'Bloqueado',
    'calendar.price': 'Preço',
    'calendar.minStay': 'Estadia Mín',
    
    // Notifications
    'notification.newBooking': 'Nova Reserva',
    'notification.paymentReceived': 'Pagamento Recebido',
    'notification.reviewReceived': 'Nova Avaliação',
    'notification.maintenanceRequest': 'Solicitação de Manutenção',
    'notification.title': 'Notificações',
    'notification.markAllRead': 'Marcar todas como lidas',
    'notification.noNotifications': 'Nenhuma notificação',
  },
  
  // French translations
  fr: {
    // Dashboard
    'dashboard.title': 'Tableau de bord',
    'dashboard.welcome': 'Bienvenue dans le Portail Propriétaire',
    'dashboard.overview': 'Aperçu',
    'dashboard.properties': 'Propriétés',
    'dashboard.bookings': 'Réservations',
    'dashboard.revenue': 'Revenus',
    'dashboard.occupancy': 'Taux d\'occupation',
    'dashboard.averageRate': 'Taux moyen',
    'dashboard.totalRevenue': 'Revenus totaux',
    'dashboard.totalBookings': 'Total des réservations',
    'dashboard.activeProperties': 'Propriétés actives',
    'dashboard.pendingReviews': 'Avis en attente',
    'dashboard.description': 'Voici ce qui se passe avec vos propriétés aujourd\'hui. Gérez votre portefeuille facilement et maximisez vos revenus locatifs.',
    'dashboard.recentBookings': 'Réservations récentes',
    'dashboard.latestReservations': 'Dernières réservations sur vos propriétés',
    'dashboard.quickActions': 'Actions rapides',
    'dashboard.manageEfficiently': 'Gérez vos propriétés efficacement',
    'dashboard.yourProperties': 'Vos propriétés',
    'dashboard.managePortfolio': 'Gérez et surveillez votre portefeuille de propriétés',
    'dashboard.viewCalendar': 'Voir le calendrier',
    'dashboard.manageBookings': 'Gérer les réservations',
    'dashboard.viewInvoices': 'Voir les factures',
    'dashboard.getSAFT': 'Obtenir SAFT-T',
    'dashboard.noBookings': 'Aucune réservation récente trouvée',
    'dashboard.bookingsWillAppear': 'Les réservations apparaîtront ici une fois que vous aurez des réservations',
    'dashboard.activePropertiesCount': 'Propriétés actives',
    'dashboard.noPropertiesFound': 'Aucune propriété trouvée',
    'dashboard.addFirstProperty': 'Ajoutez votre première propriété pour commencer à suivre les réservations et les revenus',
    'greeting.morning': 'Bonjour',
    'greeting.afternoon': 'Bon après-midi',
    'greeting.evening': 'Bonsoir',
    
    // Property Management
    'property.name': 'Nom de la propriété',
    'property.address': 'Adresse',
    'property.type': 'Type',
    'property.status': 'Statut',
    'property.guests': 'Invités max',
    'property.bedrooms': 'Chambres',
    'property.bathrooms': 'Salles de bain',
    'property.amenities': 'Équipements',
    'property.actions': 'Actions',
    'property.edit': 'Modifier',
    'property.delete': 'Supprimer',
    'property.view': 'Voir',
    'property.bookings': 'Réservations',
    'property.invoices': 'Factures',
    'property.calendar': 'Calendrier',
    'property.add': 'Ajouter une propriété',
    
    // Admin Panel
    'admin.dashboard': 'Tableau de bord administrateur',
    'admin.welcomeBack': 'Bon retour',
    'admin.allOwners': 'Tous les propriétaires',
    'admin.allAccountants': 'Tous les comptables',
    'admin.addUser': 'Ajouter un utilisateur',
    'admin.totalOwners': 'Total des propriétaires',
    'admin.totalAccountants': 'Total des comptables',
    'admin.totalProperties': 'Total des propriétés',
    'admin.totalRevenue': 'Revenus totaux',
    'admin.loadingDashboard': 'Chargement du tableau de bord administrateur...',
    'admin.ownersManagement': 'Gestion des propriétaires',
    'admin.manageOwners': 'Gérer les propriétaires et leurs informations d\'entreprise',
    'admin.addOwner': 'Ajouter un propriétaire',
    'admin.propertiesAllOwners': 'Propriétés (Tous les propriétaires)',
    'admin.managePortfolio': 'Gérer et surveiller votre portefeuille de propriétés',
    'admin.addProperty': 'Ajouter une propriété',
    'admin.accountantsAllAccountants': 'Comptables (Tous les comptables)',
    'admin.manageAccountants': 'Gérer l\'accès des comptables et les affectations de propriétés',
    'admin.noAccountants': 'Aucun comptable',
    'admin.getStartedAddAccountant': 'Commencez par ajouter un nouveau comptable',
    'admin.getStartedAddOwner': 'Commencez par ajouter votre premier propriétaire',
    'admin.getStartedAddProperty': 'Commencez par ajouter une nouvelle propriété',
    'admin.currentView': 'Vue actuelle',
    'admin.adminOwned': 'Propriété admin',
    'admin.ownerOwned': 'Propriété propriétaire',
    'admin.edit': 'Modifier',
    'admin.delete': 'Supprimer',
    'admin.verified': 'Vérifié',
    'admin.company': 'entreprise',
    'admin.companies': 'entreprises',
    'admin.pending': 'En attente',
    'admin.owner': 'Propriétaire',
    'admin.accountant': 'Comptable',
    'admin.id': 'ID',
    'admin.active': 'actif',
    
    // Bookings
    'bookings.title': 'Réservations',
    'bookings.manageReservations': 'Gérer les réservations et les communications avec les invités',
    'bookings.loading': 'Chargement des réservations...',
    'bookings.selectProperty': 'Veuillez sélectionner une propriété pour voir ses réservations.',
    'bookings.showingData': 'Affichage des données {period}',
    'bookings.forProperty': 'pour la propriété {propertyId}',
    'bookings.dateRange': '({startDate} à {endDate})',
    'bookings.clearFilters': 'Effacer les filtres',
    'bookings.property': 'Propriété:',
    'bookings.status': 'Statut',
    'bookings.allStatuses': 'Tous les statuts',
    'bookings.modified': 'Modifié',
    'bookings.inquiry': 'Enquête',
    'bookings.inquiryPreapproved': 'Enquête pré-approuvée',
    'bookings.cancelled': 'Annulé',
    'bookings.dateRangeLabel': 'Plage de dates',
    'bookings.selectDateRange': 'Sélectionner la plage de dates',
    'bookings.lastMonth': 'Le mois dernier',
    'bookings.last3Months': 'Les 3 derniers mois',
    'bookings.checkinFrom': 'Arrivée du',
    'bookings.checkinTo': 'Arrivée au',
    'bookings.clearAll': 'Tout effacer',
    'bookings.applyFilters': 'Appliquer les filtres',
    'bookings.guest': 'Invité',
    'bookings.propertyLabel': 'Propriété',
    'bookings.checkin': 'Arrivée',
    'bookings.checkout': 'Départ',
    'bookings.amount': 'Montant',
    'bookings.actions': 'Actions',
    'bookings.viewDetails': 'Voir les détails',
    'bookings.bookingDetails': 'Détails de la réservation et gestionnaire SIBA',
    'bookings.bookingInformation': 'Informations de réservation',
    'bookings.guestName': 'Nom de l\'invité:',
    'bookings.propertyColon': 'Propriété:',
    'bookings.checkinLabel': 'Arrivée:',
    'bookings.checkoutLabel': 'Départ:',
    'bookings.adults': 'Adultes:',
    'bookings.children': 'Enfants:',
    'bookings.nights': 'Nuits:',
    'bookings.platform': 'Plateforme:',
    'bookings.totalAmount': 'Montant total:',
    'bookings.noBookingsFound': 'Aucune réservation trouvée',
    'bookings.selectPropertyFirst': 'Veuillez sélectionner une propriété pour voir les réservations',
    
    // Calendar
    'calendar.title': 'Calendrier de la propriété',
    'calendar.loading': 'Chargement du calendrier...',
    'calendar.noPropertySelected': 'Aucune propriété sélectionnée',
    'calendar.selectPropertyToView': 'Veuillez sélectionner une propriété pour voir son calendrier et ses réservations.',
    'calendar.viewOnly': 'Lecture seule',
    'calendar.manageAvailability': 'Gérez la disponibilité de votre propriété et consultez les réservations',
    'calendar.viewAvailability': 'Consultez la disponibilité et les réservations (lecture seule)',
    'calendar.day.sun': 'Dim',
    'calendar.day.mon': 'Lun',
    'calendar.day.tue': 'Mar',
    'calendar.day.wed': 'Mer',
    'calendar.day.thu': 'Jeu',
    'calendar.day.fri': 'Ven',
    'calendar.day.sat': 'Sam',
    'calendar.status.booked': 'Réservé',
    'calendar.status.blocked': 'Bloqué',
    'calendar.status.available': 'Disponible',
    'calendar.status.guestDetails': 'Détails des invités',
    'calendar.selected': 'Sélectionné : {start} à {end}',
    'calendar.clickToBlockUnblock': 'Cliquez pour bloquer ou débloquer ces dates',
    'calendar.blockDates': 'Bloquer les dates',
    'calendar.unblockDates': 'Débloquer les dates',
    'calendar.cancel': 'Annuler',
    'calendar.multiDateSelection': 'Sélection multi-dates',
    'calendar.selectionInstructions': 'Cliquez sur "Commencer la sélection" → Cliquez sur la date de début → Survolez jusqu\'à la date de fin → Cliquez sur la date de fin',
    'calendar.startSelection': 'Commencer la sélection',
    'calendar.selectingDateRange': 'Sélection de la plage de dates',
    'calendar.hoverToPreview': 'Survolez pour prévisualiser la plage, puis cliquez pour terminer la sélection',
    'calendar.doubleClickMode': 'Mode double-clic : {count} date{plural} sélectionnée{plural}',
    'calendar.hoverToAdd': 'Survolez les dates pour les ajouter à la sélection',
    'calendar.blockAll': 'Tout bloquer ({count})',
    'calendar.unblockAll': 'Tout débloquer ({count})',
    'calendar.exitMode': 'Quitter le mode',
    'calendar.manageDate': 'Gérer la date',
    'calendar.selectedDate': 'Date sélectionnée :',
    'calendar.dateStatus': 'Statut de la date :',
    'calendar.unblockDate': 'Débloquer la date',
    'calendar.blockDate': 'Bloquer la date',
    'calendar.dateBookedCannotBlock': 'Cette date est réservée et ne peut pas être bloquée ou débloquée.',
    'calendar.loadingDateData': 'Chargement des données de date...',
    'calendar.loadingShort': 'Chargement...',
    'calendar.blockedCaps': 'BLOQUÉ',
    'calendar.reserved': 'RÉSERVÉ',
    'calendar.nightsMin': 'nuits min',
    'calendar.guests': 'invités',
    'calendar.onlyOwnersCanManage': 'Seuls les propriétaires peuvent gérer les dates du calendrier',
    'calendar.onlyOwnersCanManageAlert': 'Seuls les propriétaires peuvent gérer les dates du calendrier. Vous pouvez consulter le calendrier mais ne pouvez pas apporter de modifications.',
    'calendar.sessionExpired': 'Votre session a expiré. Veuillez actualiser la page pour continuer.',
    'invoices.title': 'Factures',
    'invoices.manageGuestInvoices': 'Gérer les factures des invités et la facturation',
    'invoices.loading': 'Chargement des factures...',
    'invoices.filters': 'Filtres',
    'invoices.property': 'Propriété',
    'invoices.dateRange': 'Plage de dates',
    'invoices.fromDate': 'Date de début',
    'invoices.toDate': 'Date de fin',
    'invoices.lastMonth': 'Le mois dernier',
    'invoices.last3Months': 'Les 3 derniers mois',
    'invoices.clearAll': 'Tout effacer',
    'invoices.applyFilters': 'Appliquer les filtres',
    'invoices.noInvoicesFound': 'Aucune facture trouvée',
    'invoices.noInvoicesAvailable': 'Aucune facture n\'est actuellement disponible pour cette propriété.',
    'invoices.invoice': 'Facture',
    'invoices.guest': 'Invité',
    'invoices.propertyLabel': 'Propriété',
    'invoices.date': 'Date',
    'invoices.amount': 'Montant',
    'invoices.status': 'Statut',
    'invoices.actions': 'Actions',
    'invoices.closed': 'Fermé',
    'invoices.open': 'Ouvert',
    'invoices.downloading': 'Téléchargement...',
    'invoices.downloadInvoice': 'Télécharger la facture',
    'saft.title': 'Récupération SAFT-T',
    'saft.description': 'Récupérer les fichiers SAFT (Sistema de Apuramento de Faturas e Transações) existants pour la conformité fiscale portugaise.',
    'saft.companySelection': 'Sélection de l\'entreprise',
    'saft.selectCompany': 'Sélectionner une entreprise...',
    'saft.enterNifManually': 'Ou saisir le NIF manuellement :',
    'saft.nifPlaceholder': 'ex., 234567890',
    'saft.year': 'Année',
    'saft.month': 'Mois',
    'saft.retrieving': 'Récupération...',
    'saft.retrieveSaft': 'Récupérer SAFT-T',
    'saft.downloading': 'Téléchargement...',
    'saft.downloadSaft': 'Télécharger SAFT-T',
    'saft.saftNotAvailable': 'Fichier SAFT non disponible',
    'saft.tipNotGenerated': '💡 Conseil : Les fichiers SAFT sont généralement générés à la fin de chaque mois. Essayez de sélectionner un mois précédent.',
    'saft.retrievedSuccessfully': 'SAFT-T récupéré avec succès',
    'saft.generated': 'Généré',
    'saft.sent': 'Envoyé',
    'saft.downloadSaftFile': 'Télécharger le fichier SAFT-T',
    'saft.aboutSaft': 'À propos de SAFT-T',
    'saft.aboutDescription1': 'Le SAFT-T (Sistema de Apuramento de Faturas e Transações - Transmissão) est un système de conformité fiscale portugaise qui exige que les entreprises soumettent des données de transaction détaillées aux autorités fiscales. Cet outil vous aide à récupérer les fichiers SAFT-T existants pour la période et l\'ID TVA de facturation spécifiés.',
    'saft.aboutDescription2': 'Le fichier SAFT-T contient toutes les données de facture et de transaction et peut être soumis directement aux autorités fiscales portugaises.',
    'saft.month.january': 'Janvier',
    'saft.month.february': 'Février',
    'saft.month.march': 'Mars',
    'saft.month.april': 'Avril',
    'saft.month.may': 'Mai',
    'saft.month.june': 'Juin',
    'saft.month.july': 'Juillet',
    'saft.month.august': 'Août',
    'saft.month.september': 'Septembre',
    'saft.month.october': 'Octobre',
    'saft.month.november': 'Novembre',
    'saft.month.december': 'Décembre',
    'ownerStatements.title': 'Déclarations des Propriétaires',
    'ownerStatements.description': 'Générer des déclarations financières pour les propriétaires',
    'ownerStatements.property': 'Propriété',
    'ownerStatements.selectProperty': 'Sélectionner une propriété',
    'ownerStatements.startDate': 'Date de début',
    'ownerStatements.endDate': 'Date de fin',
    'ownerStatements.managementCommissionRate': 'Taux de commission de gestion (Ignoré pour les propriétés admin)',
    'ownerStatements.generating': 'Génération...',
    'ownerStatements.generateStatements': 'Générer les déclarations',
    'ownerStatements.generatingStatements': 'Génération des déclarations...',
    'ownerStatements.propertyInformation': 'Informations sur la propriété',
    'ownerStatements.propertyName': 'Nom de la propriété :',
    'ownerStatements.propertyId': 'ID de la propriété :',
    'ownerStatements.status': 'Statut :',
    'ownerStatements.period': 'Période :',
    'ownerStatements.created': 'Créé :',
    'ownerStatements.commissionRate': 'Taux de commission :',
    'ownerStatements.detailedFinancialBreakdown': 'Répartition financière détaillée',
    'ownerStatements.downloadCsv': 'Télécharger CSV',
    'ownerStatements.downloadPdf': 'Télécharger PDF',
    'ownerStatements.detailedReport': 'RAPPORT DÉTAILLÉ',
    'ownerStatements.propertyOwner': 'Propriétaire de la Propriété',
    'ownerStatements.calculationBasis': 'Base de calcul:',
    'ownerStatements.commissionableAmount': 'Montant commissionnable:',
    'ownerStatements.commissionableAmountNote': '',
    'ownerStatements.rule': 'Règle:',
    'ownerStatements.managementCommissions': 'Commissions de gestion:',
    'ownerStatements.cleaningFees': 'Frais de nettoyage:',
    'ownerStatements.cleaningFeesNote': 'incl. TVA',
    'ownerStatements.hostCommissions': 'Commissions hôte:',
    'ownerStatements.extraFees': 'Frais supplémentaires:',
    'ownerStatements.expenses': 'Dépenses:',
    'ownerStatements.issuer': 'Émetteur:',
    'ownerStatements.recipient': 'Destinataire:',
    'ownerStatements.totalToInvoice': 'TOTAL À FACTURER:',
    'ownerStatements.tableProperty': 'Propriété',
    'ownerStatements.tableInvoice': 'Facture',
    'ownerStatements.tableReservation': 'Réservation',
    'ownerStatements.tableReceivedAmount': 'Montant reçu',
    'ownerStatements.tableHostCommission': 'Commission hôte',
    'ownerStatements.tableCleaningFee': 'Frais de nettoyage',
    'ownerStatements.tableMgmtCommission': 'Commission de gestion',
    'ownerStatements.tableTotal': 'Total',
    
    // SIBA Manager
    'sibaManager.title': 'Tableau de Bord du Gestionnaire SIBA',
    'sibaManager.underDevelopment': 'En Développement',
    'sibaManager.description': 'Nous travaillons actuellement sur l\'amélioration du Tableau de Bord du Gestionnaire SIBA avec de nouvelles fonctionnalités et améliorations. Cette section sera bientôt disponible avec des capacités complètes de surveillance de la conformité SIBA.',
    'sibaManager.comingSoon': 'Bientôt Disponible',
    
    // Auth pages
    'auth.welcomeBack': 'Bon retour',
    'auth.signInToDashboard': 'Connectez-vous à votre tableau de bord de gestion de propriétés',
    'auth.emailAddress': 'Adresse e-mail',
    'auth.enterEmail': 'Entrez votre e-mail',
    'auth.password': 'Mot de passe',
    'auth.enterPassword': 'Entrez votre mot de passe',
    'auth.sendOTP': 'Envoyer OTP',
    'auth.forgotPassword': 'Mot de passe oublié?',
    'auth.noAccount': 'Vous n\'avez pas de compte?',
    'auth.signUpFree': 'Inscrivez-vous gratuitement',
    'auth.forgotPasswordTitle': 'Mot de passe oublié?',
    'auth.forgotPasswordDescription': 'Pas de souci! Entrez votre e-mail et nous vous enverrons un OTP de réinitialisation.',
    'auth.sendResetOTP': 'Envoyer OTP de réinitialisation',
    'auth.backToLogin': 'Retour à la connexion',
    'auth.resetPasswordTitle': 'Réinitialiser votre mot de passe',
    'auth.resetPasswordDescription': 'Entrez votre e-mail, code OTP et nouveau mot de passe ci-dessous.',
    'auth.accountCreation': 'Création de Compte',
    'auth.contactAdmin': 'Contactez votre administrateur pour demander la création de compte',
    'auth.firstName': 'Prénom',
    'auth.lastName': 'Nom de famille',
    'auth.phoneNumber': 'Numéro de téléphone',
    'auth.confirmPassword': 'Confirmer le mot de passe',
    'auth.enterFirstName': 'Entrez votre prénom',
    'auth.enterLastName': 'Entrez votre nom de famille',
    'auth.enterPhoneNumber': 'Entrez votre numéro de téléphone',
    'auth.confirmYourPassword': 'Confirmez votre mot de passe',
    'auth.accountType': 'Type de compte',
    'auth.adminAccountUnavailable': 'Compte administrateur (Indisponible)',
    'auth.alreadyExists': '(Existe déjà)',
    'auth.contactAdminForAccount': 'Contacter l\'administrateur pour la création de compte',
    'auth.alreadyHaveAccount': 'Vous avez déjà un compte?',
    'auth.signInHere': 'Connectez-vous ici',
    'auth.accountCreationByAdmin': 'Création de Compte par l\'Administrateur',
    'auth.allAccountsCreatedByAdmin': 'Tous les comptes utilisateur sont créés par l\'administrateur système. Veuillez contacter votre administrateur pour demander la création de compte.',
    'auth.toRequestAccount': 'Pour demander un compte:',
    'auth.contactSystemAdmin': 'Contactez votre administrateur système',
    'auth.provideEmailAndRole': 'Fournissez votre adresse e-mail et vos exigences de rôle',
    'auth.adminWillCreateAccount': 'L\'administrateur créera votre compte et enverra les identifiants de connexion',
    'marketing.manageProperties': 'Gérez vos propriétés en toute confiance',
    'marketing.platformDescription': 'Suivez les réservations, surveillez les performances, gérez la conformité et maximisez vos revenus locatifs avec notre plateforme complète de gestion de propriétés.',
    'marketing.realTimeBooking': 'Gestion des réservations en temps réel',
    'marketing.financialTracking': 'Suivi des performances financières',
    'marketing.complianceReporting': 'Rapports de conformité automatisés',
    'marketing.multiPropertyDashboard': 'Tableau de bord multi-propriétés',
    'marketing.joinOwners': 'Rejoignez des milliers de propriétaires',
    'marketing.journeyDescription': 'Commencez votre parcours de gestion de propriétés avec notre plateforme complète conçue pour maximiser vos revenus locatifs et rationaliser les opérations.',
    'marketing.easyOnboarding': 'Intégration facile des propriétés',
    'marketing.automatedBookings': 'Gestion automatisée des réservations',
    'marketing.financialReporting': 'Rapports et analyses financiers',
    'marketing.customerSupport': 'Support client 24/7',
    
    // Booking Detail PDF
    'bookingDetail.reportTitle': 'Rapport de Détails de Réservation',
    'bookingDetail.generatedOn': 'Généré le:',
    'bookingDetail.basicInformation': 'Informations de Base',
    'bookingDetail.hostawayReservationId': 'ID de Réservation Hostaway:',
    'bookingDetail.channelReservationId': 'ID de Réservation du Canal:',
    'bookingDetail.property': 'Propriété:',
    'bookingDetail.guestName': 'Nom de l\'Invité:',
    'bookingDetail.guestEmail': 'Email de l\'Invité:',
    'bookingDetail.guestPhone': 'Téléphone de l\'Invité:',
    'bookingDetail.datesDuration': 'Dates et Durée',
    'bookingDetail.checkin': 'Arrivée:',
    'bookingDetail.checkout': 'Départ:',
    'bookingDetail.totalNights': 'Total des Nuits:',
    'bookingDetail.checkinTime': 'Heure d\'Arrivée:',
    'bookingDetail.checkoutTime': 'Heure de Départ:',
    'bookingDetail.guestInformation': 'Informations de l\'Invité',
    'bookingDetail.adults': 'Adultes:',
    'bookingDetail.children': 'Enfants:',
    'bookingDetail.totalGuests': 'Total des Invités:',
    'bookingDetail.bookingDetails': 'Détails de la Réservation',
    'bookingDetail.platform': 'Plateforme:',
    'bookingDetail.status': 'Statut:',
    'bookingDetail.paymentStatus': 'Statut du Paiement:',
    'bookingDetail.financialBreakdown': 'Analyse Financière',
    'bookingDetail.totalRevenue': 'Revenus Totaux:',
    'bookingDetail.finalAmountNote': 'Montant final - inclut tous les frais (nettoyage, taxe de séjour, etc.)',
    'bookingDetail.cityTax': 'Taxe de Séjour:',
    'bookingDetail.specialRequests': 'Demandes Spéciales',
    'bookingDetail.notProvided': 'Non fourni',
    'bookingDetail.backToBookings': 'Retour aux Réservations',
    'bookingDetail.printPdf': 'Imprimer PDF',
    'bookingDetail.guestEmailNotProvided': 'Non fourni par la plateforme (politique de confidentialité)',
    'bookingDetail.confirmed': 'Confirmé',
    'bookingDetail.modified': 'Modifié',
    'bookingDetail.cancelled': 'Annulé',
    'bookingDetail.pending': 'En attente',
    
    // Navigation
    'nav.dashboard': 'Tableau de bord',
    'nav.adminPanel': 'Panneau d\'administration',
    'nav.ownerManagement': 'Gestion des propriétaires',
    'nav.properties': 'Propriétés',
    'nav.bookings': 'Réservations',
    'nav.invoices': 'Factures',
    'nav.sibaManager': 'Gestionnaire SIBA',
    'nav.saft': 'SAFT-T',
    'nav.calendar': 'Calendrier',
    'nav.reviews': 'Avis',
    'nav.performance': 'Performance',
    'nav.portfolio': 'Portefeuille',
    'nav.creditNotes': 'Notes de crédit',
    'nav.expenses': 'Dépenses',
    'nav.ownerStatements': 'Relevés propriétaire',
    'nav.settings': 'Paramètres',
    'nav.profile': 'Profil',
    'nav.signOut': 'Se déconnecter',
    
    // Common
    'common.loading': 'Chargement...',
    'common.error': 'Erreur',
    'common.success': 'Succès',
    'common.save': 'Enregistrer',
    'common.cancel': 'Annuler',
    'common.edit': 'Modifier',
    'common.delete': 'Supprimer',
    'common.view': 'Voir',
    'common.close': 'Fermer',
    'common.yes': 'Oui',
    'common.no': 'Non',
    'common.confirm': 'Confirmer',
    'common.search': 'Rechercher',
    'common.filter': 'Filtrer',
    'common.sort': 'Trier',
    'common.refresh': 'Actualiser',
    
    // Language
    'language.english': 'English',
    'language.portuguese': 'Português',
    'language.french': 'Français',
    'language.switch': 'Changer de langue',
    
    // Status
    'status.active': 'Actif',
    'status.inactive': 'Inactif',
    'status.pending': 'En attente',
    'status.completed': 'Terminé',
    'status.cancelled': 'Annulé',
    
    // Calendar
    'calendar.month': 'Mois',
    'calendar.week': 'Semaine',
    'calendar.day': 'Jour',
    'calendar.today': 'Aujourd\'hui',
    'calendar.booked': 'Réservé',
    'calendar.available': 'Disponible',
    'calendar.blocked': 'Bloqué',
    'calendar.price': 'Prix',
    'calendar.minStay': 'Séjour min',
    
    // Notifications
    'notification.newBooking': 'Nouvelle réservation',
    'notification.paymentReceived': 'Paiement reçu',
    'notification.reviewReceived': 'Nouvel avis',
    'notification.maintenanceRequest': 'Demande de maintenance',
    'notification.title': 'Notifications',
    'notification.markAllRead': 'Tout marquer comme lu',
    'notification.noNotifications': 'Aucune notification',
  }
}

interface LanguageProviderProps {
  children: ReactNode
}

export const LanguageProvider: React.FC<LanguageProviderProps> = ({ children }) => {
  const [language, setLanguage] = useState<Language>(() => {
    // Get language from localStorage or default to English
    const savedLanguage = localStorage.getItem('language') as Language
    return savedLanguage && ['en', 'pt', 'fr'].includes(savedLanguage) ? savedLanguage : 'en'
  })

  useEffect(() => {
    // Save language to localStorage whenever it changes
    localStorage.setItem('language', language)
  }, [language])

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations[typeof language]] || key
  }

  const value: LanguageContextType = {
    language,
    setLanguage,
    t
  }

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  )
}

export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider')
  }
  return context
}
