### Hostaway Access Token Request
POST https://api.hostaway.com/v1/accessTokens
Content-Type: application/x-www-form-urlencoded

grant_type=client_credentials&client_id=123645&client_secret=1946908c9b294ed62e0de83a72e40c16856a83dca87a724ed5a4371afbbd8120&scope=general


### Test backend calendar endpoint
### Get Calendar data from Hostaway directly
GET https://api.hostaway.com/v1/listings/392776/calendar?startDate=2025-01-01&endDate=2025-12-31&includeResources=1
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxMjM2NDUiLCJqdGkiOiJlODQ4OGQ4ZDJjZTFmNDYyZDYzMGM1Yzg4MTg4NzcwYjUxNGRjYWFmNTAyNzQzYjZjMzYyZDE4YzIyODlkMTRmZDIzYmYwNmNkODVhYTUwMCIsImlhdCI6MTc1NTA2OTQ2Mi4wOTg3MjYsIm5iZiI6MTc1NTA2OTQ2Mi4wOTg3MjgsImV4cCI6MjA3MDYwMjI2Mi4wOTg3MzMsInN1YiI6IiIsInNjb3BlcyI6WyJnZW5lcmFsIl0sInNlY3JldElkIjo2OTMyNX0.W0XRyKopiDXAOfBJnuTfdVKt1S5cmSKC4bqPv5VY00VLCbACceUTH2cdmThL5ZpU8-AmLk6PicGOrjfuPqq3QBO4RoFqTXAUMIrQlgG2EOHpA-S07ua068oNlnubWkfmTheMY_eHf19dZOndKqf3c4NKA9EYINP7FD-Q30ypdSLMnUzb9URVztNbt6cDPgog2cqVDJo919evo3q-zunel0qX8jG_whfalJoTBLx3InGOQb3_8L8uY7qHKfS9Lq8j-q_3wvUDz_1ogoanE0ncePVdhRhQazkhzwkH5NOWokcx83qimsEnZUWRGpH3yelcqOQvDsyUoQuvMCdL4reqbQ

###
GET https://api.hostaway.com/v1/listings
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxMjM2NDUiLCJqdGkiOiJlODQ4OGQ4ZDJjZTFmNDYyZDYzMGM1Yzg4MTg4NzcwYjUxNGRjYWFmNTAyNzQzYjZjMzYyZDE4YzIyODlkMTRmZDIzYmYwNmNkODVhYTUwMCIsImlhdCI6MTc1NTA2OTQ2Mi4wOTg3MjYsIm5iZiI6MTc1NTA2OTQ2Mi4wOTg3MjgsImV4cCI6MjA3MDYwMjI2Mi4wOTg3MzMsInN1YiI6IiIsInNjb3BlcyI6WyJnZW5lcmFsIl0sInNlY3JldElkIjo2OTMyNX0.W0XRyKopiDXAOfBJnuTfdVKt1S5cmSKC4bqPv5VY00VLCbACceUTH2cdmThL5ZpU8-AmLk6PicGOrjfuPqq3QBO4RoFqTXAUMIrQlgG2EOHpA-S07ua068oNlnubWkfmTheMY_eHf19dZOndKqf3c4NKA9EYINP7FD-Q30ypdSLMnUzb9URVztNbt6cDPgog2cqVDJo919evo3q-zunel0qX8jG_whfalJoTBLx3InGOQb3_8L8uY7qHKfS9Lq8j-q_3wvUDz_1ogoanE0ncePVdhRhQazkhzwkH5NOWokcx83qimsEnZUWRGpH3yelcqOQvDsyUoQuvMCdL4reqbQ 


###
GET https://api.hostaway.com/v1/calendar?propertyId=392776&startDate=2025-01-01&endDate=2025-12-31&includeResources=1
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxMjM2NDUiLCJqdGkiOiJlODQ4OGQ4ZDJjZTFmNDYyZDYzMGM1Yzg4MTg4NzcwYjUxNGRjYWFmNTAyNzQzYjZjMzYyZDE4YzIyODlkMTRmZDIzYmYwNmNkODVhYTUwMCIsImlhdCI6MTc1NTA2OTQ2Mi4wOTg3MjYsIm5iZiI6MTc1NTA2OTQ2Mi4wOTg3MjgsImV4cCI6MjA3MDYwMjI2Mi4wOTg3MzMsInN1YiI6IiIsInNjb3BlcyI6WyJnZW5lcmFsIl0sInNlY3JldElkIjo2OTMyNX0.W0XRyKopiDXAOfBJnuTfdVKt1S5cmSKC4bqPv5VY00VLCbACceUTH2cdmThL5ZpU8-AmLk6PicGOrjfuPqq3QBO4RoFqTXAUMIrQlgG2EOHpA-S07ua068oNlnubWkfmTheMY_eHf19dZOndKqf3c4NKA9EYINP7FD-Q30ypdSLMnUzb9URVztNbt6cDPgog2cqVDJo919evo3q-zunel0qX8jG_whfalJoTBLx3InGOQb3_8L8uY7qHKfS9Lq8j-q_3wvUDz_1ogoanE0ncePVdhRhQazkhzwkH5NOWokcx83qimsEnZUWRGpH3yelcqOQvDsyUoQuvMCdL4reqbQ




###Test hostkit url
get https://app.hostkit.pt/api/getProperties?APIKEY=1K2Ni9NRPexjJuHlX_MsA9g3PZw8S2cRr3XykY9c6Hui1AaPk8&account_id=123645
