// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vbfvlcuqoinkafqknysp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZiZnZsY3Vxb2lua2FmcWtueXNwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg1NjQ1MTEsImV4cCI6MjA2NDE0MDUxMX0.RMVra_nETrVKUHhF_GUrouzSaiRtZdlChFTTA79ijSw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);