name: MongoDB Keep-Alive

on:
  schedule:
    # Run every 15 minutes (GitHub's minimum interval)
    - cron: '*/15 * * * *'
    # Run every 30 minutes as backup
    - cron: '*/30 * * * *'
    # Run every hour as additional backup
    - cron: '0 * * * *'
    # Run every 2 hours as final backup
    - cron: '0 */2 * * *'
  workflow_dispatch: # Allow manual trigger
  push: # Also run on push to ensure it's active
  pull_request: # Trigger on PRs to keep repo active

jobs:
  keep-alive:
    runs-on: ubuntu-latest
    steps:
      - name: Ping MongoDB and Auth Services
        run: |
          echo "🔄 Running keep-alive at $(date)"
          
          # Ping MongoDB keep-alive
          curl -X POST "https://smarthoster-test-deploy.vercel.app/api/cron/keep-alive" \
            -H "Content-Type: application/json" \
            -w "\nMongoDB Status: %{http_code}\n"
          
          # Ping Auth OTP endpoint (with invalid email to just wake it up)
          curl -X POST "https://smarthoster-test-deploy.vercel.app/auth/send-login-otp" \
            -H "Content-Type: application/json" \
            -d '{"email":"keepalive@test.com"}' \
            -w "\nAuth OTP Status: %{http_code}\n" || true
          
          echo "✅ Keep-alive completed at $(date)"
